apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ventas-app
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: 'https://github.com/diegonayalazo/school-app-repo.git'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ventas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
